CodeZoneDemoProject/Models/ErrorViewModel.cs
namespace CodeZoneDemoProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodeZoneDemoProject/Controllers/AddStockController.cs
using CodeZoneProject.Application.Items.Queries;
using CodeZoneProject.Application.StoreItems.Commands;
using CodeZoneProject.Application.StoreItems.Queries;
using CodeZoneProject.Application.Stores.Queries;
using CodeZoneProject.Domain.Entities;
using CodeZoneProject.Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CodeZoneProject.Web.Controllers
{
    public class AddStockController : BaseController
    {
        public async Task<IActionResult> Index()
        {
            var items = await Mediator.Send(new GetAllItemsQuery());
            var stores = await Mediator.Send(new GetAllStoresQuery());
            ViewBag.Items = new SelectList(items, "Id", "Name");
            ViewBag.Stores = new SelectList(stores, "Id", "Name");
            return View();
        }

        #region APIs
        public async Task<IActionResult> GetStoreItemQuantity(Guid storeId, Guid itemId)
        {
            return await Execute(new GetStoreItemQuantityQuery() { ItemId = itemId , StoreId = storeId }, "GetStoreItemQuantityQuery");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStoreItemQuantity([FromBody]UpdateStoreItemQuantityCommand command)
        {
            return await Execute(command, "GetStoreItemQuantityQuery");
        }
        #endregion
    }
}

CodeZoneDemoProject/Controllers/BaseController.cs
using CodeZoneProject.Application.Items.Commands.Create;
using CodeZoneProject.Infrastructure;
using FluentValidation;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace CodeZoneProject.Web.Controllers
{
    public class BaseController : Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ?? (_mediator = HttpContext.RequestServices.GetService<IMediator>());
        public async Task<ActionResult> Execute<TRequest>(IRequest<TRequest> request, string Msg)
        {
            try
            {
                var response = await Mediator.Send(request);
                return Ok(new JsonResponse<TRequest> { Data = response, Message = Msg, StatusCode = (int)HttpStatusCode.OK, Success = true });
            }

            catch (Exception ex)
            { return BadRequest(new JsonResponse<int> { Data = 0, Message = ex.Message, StatusCode = (int)HttpStatusCode.BadRequest }); }
        }

        public async Task<ActionResult> ValidateAndProcessCommand<TCommand, TValidator>(TCommand command)
            where TValidator : AbstractValidator<TCommand>, new()
        {
            var validator = new TValidator();
            var validationResult = await validator.ValidateAsync(command);

            if (validationResult.IsValid)
            {
                await Mediator.Send(command);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(command);
            }
        }
    }
}

CodeZoneDemoProject/Controllers/HomeController.cs
using CodeZoneDemoProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CodeZoneDemoProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeZoneDemoProject/Controllers/StoresController.cs
using CodeZoneProject.Application.Items.Commands.Create;
using CodeZoneProject.Application.Items.Commands.Delete;
using CodeZoneProject.Application.Stores.Commands.Create;
using CodeZoneProject.Application.Stores.Commands.Delete;
using CodeZoneProject.Application.Stores.Commands.Update;
using CodeZoneProject.Application.Stores.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace CodeZoneProject.Web.Controllers
{
    public class StoresController : BaseController
    {
        public async Task<ActionResult> Index()
        {
            ViewBag.Stores = await Mediator.Send(new GetAllStoresQuery());
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateStoreCommand command)
        {
            try
            {
                return await ValidateAndProcessCommand<CreateStoreCommand, CreateStoreCommandValidator>(command);
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Edit(Guid id)
        {
            var store = await Mediator.Send(new GetStoreByIdQuery() { Id = id });
            if (store != null)
                return View(new UpdateStoreCommand()
                {
                    Id = store.Id,
                    Name = store.Name,
                    Address = store.Address
                });

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<ActionResult> Edit(UpdateStoreCommand command)
        {
            try
            {
                return await ValidateAndProcessCommand<UpdateStoreCommand, UpdateStoreCommandValidator>(command);
            }
            catch
            {
                return View(command);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(Guid id)
        {
            var result = await Mediator.Send(new DeleteStoreCommand() { Id = id });
            if (result)
                return Ok();
            else
                return BadRequest();
        }
    }
}

CodeZoneDemoProject/Views/AddStock/Index.cshtml
@{
    var title = "Add Stock";
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <section id="file-export">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="heading-elements">
                                    <h3 class="content-header-title">@title</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-md-5">
                                        <label class="control-label">Store</label>
                                        <select onchange="getCurrentQuantity()" id="StoreId" asp-items="ViewBag.Stores" type="text" class="form-control">
                                            <option value="" disabled selected>select store</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-5">
                                        <label class="control-label text-danger" id="validationError"></label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-5">
                                        <label class="control-label">Item</label>
                                        <select onchange="getCurrentQuantity()" id="ItemId" asp-items="ViewBag.Items" type="text" class="form-control">
                                            <option value="" disabled selected>select item</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label class="control-label">Quantity</label>
                                        <input type="number" id="Quantity" class="form-control">
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label class="control-label">Store Quantity</label>
                                        <input readonly id="StoreQuantity" type="text" class="form-control">
                                    </div>
                                    <div class="form-group col-md-1">
                                        <label class="control-label"></label>
                                        <button class="btn btn-primary form-control" onclick="modifiyStock()">modifiy</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
@section Scripts {
    @{
        <script>
            let getCurrentQuantity = function () {
                let itemId = $("#ItemId").val();
                let storeId = $("#StoreId").val();
                
                $.ajax({
                    url: `/AddStock/GetStoreItemQuantity?ItemId=${itemId}&storeId=${storeId}`,
                    dataType: 'json',
                    type: 'GET',
                    success: function (response) {
                        $("#StoreQuantity").val(response.data)
                    }
                });
                
            }

            let modifiyStock = function(){


                if ($("#StoreId").val() === null) {
                    $("#validationError").text("Select Store")
                } else if ($("#ItemId").val() === null) {
                    $("#validationError").text("Select Item")
                } else if ($("#Quantity").val() === "") {
                    $("#validationError").text("Enter Quantity")
                }else{
                    $("#validationError").text("")

                    let command ={
                        itemId : $("#ItemId").val(),
                        storeId : $("#StoreId").val(),
                        quantity : $("#Quantity").val()
                    }

                    $.ajax({
                        url: `/AddStock/UpdateStoreItemQuantity`,
                        dataType: 'json',
                        type: 'POST',
                        contentType: "application/json",
                        data: JSON.stringify(command),
                        success: function (response) {
                            getCurrentQuantity()
                        }
                    });
                }
                
            }
        </script>
    }
}

CodeZoneDemoProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodeZoneDemoProject/Views/Items/Create.cshtml
@model CodeZoneProject.Application.Items.Commands.Create.CreateItemCommand
@{
    var title = "Create Item";
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <section id="file-export">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="heading-elements">
                                    <h3 class="content-header-title">@title</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <form asp-action="Create">
                                    <div class="row">
                                        <div class="form-group col-6">
                                            <label class="control-label">Name</label>
                                            <input asp-for="Name" required type="text" class="form-control">
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        <div class="form-group col-6">
                                            <label class="control-label">Category</label>
                                            <select asp-for="Category" asp-items="ViewBag.Categories" type="text" class="form-control"></select>
                                            <span asp-validation-for="Category" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-group col-6 mt-3">
                                        <button class="btn btn-primary">
                                            Save
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CodeZoneDemoProject/Views/Items/Edit.cshtml
@model CodeZoneProject.Application.Items.Commands.Update.UpdateItemCommand
@{
    var title = "Update Item";
    var x = Model;
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <section id="file-export">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="heading-elements">
                                    <h3 class="content-header-title">@title</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <form asp-action="Edit" method="post">
                                    <div class="row">
                                        <input asp-for="Id" hidden type="text" class="form-control">

                                        <div class="form-group col-6">
                                            <label class="control-label">Name</label>
                                            <input asp-for="Name" type="text" class="form-control">
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        <div class="form-group col-6">
                                            <label class="control-label">Category</label>
                                            <select asp-for="Category" asp-items="ViewBag.Categories" type="text" class="form-control"></select>
                                            <span asp-validation-for="Category" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-group col-6 mt-3">
                                        <button class="btn btn-primary">
                                            Save
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

CodeZoneDemoProject/Views/Items/Index.cshtml
@{
    var title = "Items";
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between">
                                <h3 class="content-header-title">@title</h3>
                                <a class='mr-1 mb-1 btn btn-dark' href="/items/create">create</a>
                            </div>

                        </div>
                        <div class="card-body">
                            <table class="table Stagedt table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <td>Name</td>
                                        <td>Category</td>
                                        <td>Actions</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach(var item in ViewBag.Items)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Category</td>
                                            <td>
                                                <a class='mr-1 mb-1 btn btn-primary' href="/items/edit/@item.Id.ToString()">edit</a>
                                                <a class='mr-1 mb-1 btn btn-danger' id="@item.Id.ToString()" onclick="Delete(this)">delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        let Delete = function (obj) {
            let Id = $(obj).attr("id")
            if(confirm('Are you sure you want to delete?')){
                $.ajax({
                    url: `/Items/Delete/${Id}`,
                    dataType: 'json',
                    type: "Get",
                    success: function (response) {
                        alert('Deleted Successfully');
                        location.reload();
                    },
                    error: function (err) {
                        alert("error in deleting");
                        location.reload();
                    }
                });
            }

        }
    </script>
}

CodeZoneDemoProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeZoneDemoProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodeZoneDemoProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodeZoneDemoProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Stores" asp-action="Index">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Items" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="AddStock" asp-action="Index">Add Stock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CodeZoneDemoProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CodeZoneDemoProject/Views/Stores/Create.cshtml
@model CodeZoneProject.Application.Items.Commands.Create.CreateItemCommand
@{
    var title = "Create Item";
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <section id="file-export">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="heading-elements">
                                    <h3 class="content-header-title">@title</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <form asp-action="Create">
                                    <div class="row">
                                        <div class="form-group col-6">
                                            <label class="control-label">Name</label>
                                            <input asp-for="Name" type="text" class="form-control">
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        <div class="form-group col-6">
                                            <label class="control-label">Category</label>
                                            <select asp-for="Category" asp-items="ViewBag.Categories" type="text" class="form-control"></select>
                                            <span asp-validation-for="Category" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-group col-6 mt-3">
                                        <button class="btn btn-primary">
                                            Save
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
@{Html.RenderPartialAsync("_ValidationScriptsPartial");}

CodeZoneDemoProject/Views/Stores/Edit.cshtml
@model CodeZoneProject.Application.Stores.Commands.Update.UpdateStoreCommand
@{
    var title = "Update Store";
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <section id="file-export">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="heading-elements">
                                    <h3 class="content-header-title">@title</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <form asp-action="Edit" method="post">
                                    <div class="row">
                                        <input asp-for="Id" hidden type="text" class="form-control">

                                        <div class="form-group col-6">
                                            <label class="control-label">Name</label>
                                            <input asp-for="Name" type="text" class="form-control">
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        <div class="form-group col-6">
                                            <label class="control-label">Address</label>
                                            <input asp-for="Address" type="text" class="form-control">
                                            <span asp-validation-for="Address" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-group col-6 mt-3">
                                        <button class="btn btn-primary">
                                            Save
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

CodeZoneDemoProject/Views/Stores/Index.cshtml
@{
    var title = "Stores";
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between">
                                <h3 class="content-header-title">@title</h3>
                                <a class='mr-1 mb-1 btn btn-dark' href="/Stores/create">create</a>
                            </div>

                        </div>
                        <div class="card-body">
                            <table class="table Stagedt table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <td>Name</td>
                                        <td>Address</td>
                                        <td>Actions</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var store in ViewBag.Stores)
                                    {
                                        <tr>
                                            <td>@store.Name</td>
                                            <td>@store.Address</td>
                                            <td>
                                                <a class='mr-1 mb-1 btn btn-primary' href="/Stores/edit/@store.Id.ToString()">edit</a>
                                                <a class='mr-1 mb-1 btn btn-danger' id="@store.Id.ToString()" onclick="Delete(this)">delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        let Delete = function (obj) {
            let Id = $(obj).attr("id")
            if (confirm('Are you sure you want to delete?')) {
                $.ajax({
                    url: `/Stores/Delete/${Id}`,
                    dataType: 'json',
                    contentType: "application/json",
                    type: "Get",
                    success: function (response) {
                        alert('Deleted Successfully');
                        location.reload();
                    },
                    error: function (err) {
                        console.log(err)
                        alert("error in deleting");
                        location.reload();
                    }
                });
            }

        }
    </script>
}